"""自动生成 — breast 结构化模板"""
from template_converted import register_templates

_TPL = {
    '乳腺（不是1级）': {
        'html': '<div class="rpt-sec">双侧乳腺切面形态轮廓正常，层次清楚，边界光滑完整，内部回声分布均匀，未见明显结节及其它异常回声。</div>',
        'fields': {},
        'measurements': [],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '乳腺囊肿（单发）': {
        'html': '<div class="rpt-sec">双侧乳腺切面形态轮廓正常，层次清楚，边界光滑完整，内部回声分布均匀，左乳/右乳  点处可探及一无回声结节，大小{_size_0}mm，形态规则，壁薄，后壁回声增强，内透声可。</div>',
        'fields': {"_size_0": "无回声结节，大小"},
        'measurements': [["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '双乳多发囊肿': {
        'html': '<div class="rpt-sec">双侧乳腺切面形态轮廓正常，层次清楚，边界光滑完整，内部回声分布均匀，双乳内可探及多个无回声结节，左乳 点处较大{_较大_0}mm、右乳 点处较大{_较大_1}mm，形态规则，壁薄，后壁回声增强。</div>',
        'fields': {"_较大_0": "，左乳 点处较大", "_较大_1": "、右乳 点处较大"},
        'measurements': [["(?:点处较大)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_较大_0"], ["(?:点处较大)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_较大_1"]],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '双乳多发结节（脑科医院）': {
        'html': '<div class="rpt-sec">双侧乳腺切面形态轮廓正常，层次清楚，边界光滑完整，内部回声分布均匀，双乳内可探及多个低回声结节，其一大小分别{_size_0}mm（位于左乳 点）、{_乳点_1}mm（位于右乳 点），形态规则，边界清晰，内部回声均匀。</div>',
        'fields': {"_size_0": "节，其一大小分别", "_乳点_1": "位于左乳 点）、"},
        'measurements': [["(?:其一大小分别)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"], ["(?:点)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_乳点_1"]],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '哺乳期乳腺': {
        'html': '<div class="rpt-sec">双侧乳腺腺体层增厚，腺体回声增强，可见部分乳管扩张,乳腺腺体可见含液体性包块，未见明显实质性肿块。</div>\n<div class="rpt-sec">CDFI：双乳内无异常血流信号。</div>\n<div class="rpt-sec">双侧腋窝未见明显肿大淋巴结声像。</div>',
        'fields': {},
        'measurements': [],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '乳腺纤维瘤': {
        'html': '<div class="rpt-sec">双侧乳腺切面形态轮廓正常，层次清楚，边界光滑完整，内部回声分布均匀，左乳/右乳  点处可探及一大小{_size_0}mm低回声/等回声区，形态规则，边界清晰，包膜完整，内部回声均匀。</div>',
        'fields': {"_size_0": "点处可探及一大小"},
        'measurements': [["(?:点处可探及一大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '乳腺多发结节（脑科医院）': {
        'html': '<div class="rpt-sec">双侧乳腺切面形态轮廓正常，层次清楚，边界光滑完整，内部回声分布均匀，左乳/右乳可探及多个低回声结节，其一大小{_size_0}mm（位于 点），形态规则，边界清晰，内部回声欠均匀。</div>',
        'fields': {"_size_0": "声结节，其一大小"},
        'measurements': [["(?:其一大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '双侧乳腺未见占位性病变，BI-RADS 1类。': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '乳腺结节单发': {
        'html': '<div class="rpt-sec">双侧乳腺切面形态轮廓正常，层次清楚，边界光滑完整，内部回声分布均匀，左乳/右乳  点可探及一低回声结节，大小{_size_0}mm，形态规则，边界清晰，内部回声欠均匀。</div>',
        'fields': {"_size_0": "低回声结节，大小"},
        'measurements': [["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '乳腺结节（310）': {
        'html': '<div class="rpt-sec">双侧乳腺切面形态轮廓正常，层次清楚，边界光滑完整，内部回声分布均匀，右乳 点处可见低回声结节，大小约  ，边界清，形态规则，内回声欠均匀。</div>',
        'fields': {},
        'measurements': [],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '乳腺导管扩张': {
        'html': '<div class="rpt-sec">左/右侧乳腺局部导管扩张，较宽处{_width_0}mm。</div>',
        'fields': {"_width_0": "导管扩张，较宽处"},
        'measurements': [["(?:较宽处)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_width_0"]],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '腋窝淋巴结正常': {
        'html': '<div class="rpt-sec">双侧腋窝未见明显肿大淋巴结声像。</div>',
        'fields': {},
        'measurements': [],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '腋窝淋巴结异常': {
        'html': '<div class="rpt-sec">左/右侧腋窝可见低回声结节，大小{_size_0}mm，形态规则，边界清，门样结构存在/消失。</div>',
        'fields': {"_size_0": "低回声结节，大小"},
        'measurements': [["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [["规则", "_norm_规则"]],
        'opt_reset': {},
        'option_keys': ["_norm_规则"],
    },
    '左/右侧腋窝低回声结节，考虑淋巴结。': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '以脂肪为主型乳腺（1类）': {
        'html': '<div class="rpt-sec">双乳脂肪组织增厚，腺体增粗，回声分布不均，见多个粗大点片状低回声区，呈“豹纹征”。</div>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '双侧乳腺增生': {
        'html': '<div class="rpt-sec">乳腺容积图像位置、深度和分辨率合格，未见伪像。</div>',
        'fields': {},
        'measurements': [],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '双侧乳腺声像 考虑 BI-RADS 1类': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '乳腺囊肿（单侧）': {
        'html': '<div class="rpt-sec">乳腺容积图像位置、深度和分辨率合格，未见伪像。</div>',
        'fields': {},
        'measurements': [],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '乳无回声区BI-RADS 2类(考虑乳腺囊肿)': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '乳腺囊肿（双侧）': {
        'html': '<div class="rpt-sec">乳腺容积图像位置、深度和分辨率合格，未见伪像。</div>',
        'fields': {},
        'measurements': [],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '乳腺增生结节': {
        'html': '<div class="rpt-sec">乳腺容积图像位置、深度和分辨率合格，未见伪像。</div>',
        'fields': {},
        'measurements': [],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '纤维腺瘤（单侧）': {
        'html': '<div class="rpt-sec">乳腺容积图像位置、深度和分辨率合格，未见伪像。</div>',
        'fields': {},
        'measurements': [],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '纤维腺瘤（双侧）': {
        'html': '<div class="rpt-sec">乳腺容积图像位置、深度和分辨率合格，未见伪像。</div>',
        'fields': {},
        'measurements': [],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '乳腺4c类肿块': {
        'html': '<div class="rpt-sec">乳腺容积图像位置、深度和分辨率合格，未见伪像。</div>',
        'fields': {},
        'measurements': [],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '腋窝淋巴结异常模板（陈）': {
        'html': '<div class="rpt-sec">左/右侧腋窝可见一大小{_size_0}mm低回声结节。</div>',
        'fields': {"_size_0": "侧腋窝可见一大小"},
        'measurements': [["(?:右侧腋窝可见一大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '乳腺结节（陈）': {
        'html': '<div class="rpt-sec">双侧乳腺切面形态轮廓正常，层次清楚，边界光滑完整，内部回声分布均匀，左乳/右乳 点距乳头{_乳头_0}mm、距体表{_体表_1}mm处可探及一低回声结节，大小{_size_2}mm，形态规则，边界清晰，内部回声欠均匀，左乳/右乳内未见明显结节及包块声像。</div>',
        'fields': {"_乳头_0": "/右乳 点距乳头", "_体表_1": "头约mm、距体表", "_size_2": "低回声结节，大小"},
        'measurements': [["(?:点距乳头)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_乳头_0"], ["(?:距体表)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_体表_1"], ["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_2"]],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '乳腺结节（无回声）': {
        'html': '<div class="rpt-sec">双侧乳腺切面形态轮廓正常，层次清楚，边界光滑完整，内部回声分布均匀，左乳/右乳  点可探及一无回声结节，大小{_size_0}mm，形态规则，边界清晰，内透声可。</div>',
        'fields': {"_size_0": "无回声结节，大小"},
        'measurements': [["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '副乳': {
        'html': '<div class="rpt-sec">左/右侧腋窝可见范围{_范围_0}mm低回声区，类似乳腺组织声像。</div>',
        'fields': {"_范围_0": "右侧腋窝可见范围"},
        'measurements': [["(?:右侧腋窝可见范围)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_范围_0"]],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '双侧腋窝淋巴结异常': {
        'html': '<div class="rpt-sec">双侧腋窝可见低回声结节，大小{_size_0}mm（左），{_size_1}mm（右），形态规则，边界清，门样结构存在/消失。</div>',
        'fields': {"_size_0": "低回声结节，大小", "_size_1": "约 mm（左），"},
        'measurements': [["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"], ["(?:左)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_1"]],
        'options': [["规则", "_norm_规则"]],
        'opt_reset': {},
        'option_keys': ["_norm_规则"],
    },
    '双侧腋窝低回声结节，考虑淋巴结。': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '乳腺低-无回声区': {
        'html': '<div class="rpt-sec">双侧乳腺切面形态轮廓正常，层次清楚，边界光滑完整，内部回声分布均匀，左乳/右乳可探及一低-无回声区，大小{_size_0}mm，形态规则，边界清晰，内部回声欠均匀。</div>',
        'fields': {"_size_0": "-无回声区，大小"},
        'measurements': [["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '乳腺无回声单模板': {
        'html': '<div class="rpt-sec">左乳/右乳  点可探及一无回声结节，大小{_size_0}mm，形态规则，边界清晰，内透声可。</div>',
        'fields': {"_size_0": "无回声结节，大小"},
        'measurements': [["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [["规则", "_norm_规则"]],
        'opt_reset': {},
        'option_keys': ["_norm_规则"],
    },
    '乳腺实质性-ch': {
        'html': '<div class="rpt-sec">双侧乳腺切面形态轮廓正常，层次清楚，边界光滑完整，内部回声分布均匀，左乳/右乳  点可探及一低回声结节，大小{_size_0}mm，形态规则，边界清晰，内部回声欠均匀。</div>',
        'fields': {"_size_0": "低回声结节，大小"},
        'measurements': [["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '乳腺囊性结节-ch': {
        'html': '<div class="rpt-sec">双侧乳腺切面形态轮廓正常，层次清楚，边界光滑完整，内部回声分布均匀，左乳/右乳  点可探及一囊性结节，大小{_size_0}mm，形态规则，边界清晰，内透声可。</div>',
        'fields': {"_size_0": "一囊性结节，大小"},
        'measurements': [["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '乳腺多发结节（无回声）': {
        'html': '<div class="rpt-sec">双侧乳腺切面形态轮廓正常，层次清楚，边界光滑完整，内部回声分布均匀，左乳/右乳可探及多个无回声结节，其一大小{_size_0}mm（位于 点），形态规则，边界清晰，内透声可。</div>',
        'fields': {"_size_0": "声结节，其一大小"},
        'measurements': [["(?:其一大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '乳腺多发囊性结节-CH': {
        'html': '<div class="rpt-sec">双侧乳腺切面形态轮廓正常，层次清楚，边界光滑完整，内部回声分布均匀，左乳/右乳/双乳可探及多个囊性结节，较大位于 点，大小{_size_0}mm，形态规则，边界清晰，内透声可。</div>',
        'fields': {"_size_0": "大位于 点，大小"},
        'measurements': [["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '乳腺假体-CH': {
        'html': '<div class="rpt-sec">双侧假体术后：双乳组织增厚、增粗，回声分布不均，见多个粗大点片状低回声区，呈“豹纹征”。</div>\n<div class="rpt-sec">双侧乳腺后间隙可见假体回声，内透声可。</div>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '乳腺多发无回声结节-LD': {
        'html': '<div class="rpt-sec">双侧乳腺切面形态轮廓正常，层次清楚，边界光滑完整，内部回声分布均匀，双乳可探及多个无回声结节，其一大小{_size_0}mm（右乳 点，距乳头{_乳头_1}mm处/乳头旁/乳头后方）、{_后方_2}mm（左乳 点，距乳头{_乳头_3}mm处/乳头旁/乳头后方），形态规则，边界清晰，内透声可。</div>',
        'fields': {"_size_0": "声结节，其一大小", "_乳头_1": "右乳 点，距乳头", "_后方_2": "旁/乳头后方）、", "_乳头_3": "左乳 点，距乳头"},
        'measurements': [["(?:其一大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"], ["(?:距乳头)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_乳头_1"], ["(?:乳头后方)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_后方_2"], ["(?:距乳头)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_乳头_3"]],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '乳腺无回声结节-LD': {
        'html': '<div class="rpt-sec">双侧乳腺切面形态轮廓正常，层次清楚，边界光滑完整，内部回声分布均匀，左乳/右乳  点距乳头{_乳头_0}mm处/乳头旁/乳头后方可探及一无回声结节，大小{_size_1}mm，形态规则，壁薄，后壁回声增强，内透声可。</div>',
        'fields': {"_乳头_0": "右乳  点距乳头", "_size_1": "无回声结节，大小"},
        'measurements': [["(?:点距乳头)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_乳头_0"], ["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_1"]],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '双乳低回声结节-LD': {
        'html': '<div class="rpt-sec">双侧乳腺切面形态轮廓正常，层次清楚，边界光滑完整，内部回声分布均匀，左乳/右乳  点距乳头{_乳头_0}mm处/乳头旁/乳头后方可探及一低回声结节，大小{_size_1}mm，形态规则，边界清晰，内部回声欠均匀。</div>',
        'fields': {"_乳头_0": "右乳  点距乳头", "_size_1": "低回声结节，大小"},
        'measurements': [["(?:点距乳头)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_乳头_0"], ["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_1"]],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '双乳多发低回声结节-LD': {
        'html': '<div class="rpt-sec">双侧乳腺切面形态轮廓正常，层次清楚，边界光滑完整，内部回声分布均匀，双乳可探及多个低回声结节，其一大小{_size_0}mm（右乳 点，距乳头{_乳头_1}mm处/乳头旁/乳头后方）、{_后方_2}mm（左乳 点，距乳头{_乳头_3}mm处/乳头旁/乳头后方），形态规则，边界清晰，内回声均匀。</div>',
        'fields': {"_size_0": "声结节，其一大小", "_乳头_1": "右乳 点，距乳头", "_后方_2": "旁/乳头后方）、", "_乳头_3": "左乳 点，距乳头"},
        'measurements': [["(?:其一大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"], ["(?:距乳头)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_乳头_1"], ["(?:乳头后方)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_后方_2"], ["(?:距乳头)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_乳头_3"]],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '左/右乳低回声结节-LD': {
        'html': '<div class="rpt-sec">左乳/右乳  点距乳头{_乳头_0}mm处/乳头旁/乳头后方可探及一低回声结节，大小{_size_1}mm，形态规则，边界清晰，内部回声欠均匀。</div>',
        'fields': {"_乳头_0": "右乳  点距乳头", "_size_1": "低回声结节，大小"},
        'measurements': [["(?:点距乳头)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_乳头_0"], ["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_1"]],
        'options': [["规则", "_norm_规则"]],
        'opt_reset': {},
        'option_keys': ["_norm_规则"],
    },
    '左/右乳无回声结节LD': {
        'html': '<div class="rpt-sec">左乳/右乳  点距乳头{_乳头_0}mm处/乳头旁/乳头后方可探及一无回声结节，大小{_size_1}mm，形态规则，壁薄，后壁回声增强，内透声可。</div>',
        'fields': {"_乳头_0": "右乳  点距乳头", "_size_1": "无回声结节，大小"},
        'measurements': [["(?:点距乳头)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_乳头_0"], ["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_1"]],
        'options': [["规则", "_norm_规则"]],
        'opt_reset': {},
        'option_keys': ["_norm_规则"],
    },
    '膀胱肿瘤：表浅型(附二)': {
        'html': '<div class="rpt-sec">膀胱切面形态轮廓失常，膀胱三角区局限性增厚，可见一个大小{_size_0}mm呈常回声，突向膀胱腔内，形状呈乳头状，内部为低回声，并可见点状强回声，分布均质，后方回声无变化，改变体位不移动，有蒂，基底较窄，附着处膀胱壁回声带光滑整齐，连续性好。</div>',
        'fields': {"_size_0": "厚，可见一个大小"},
        'measurements': [["(?:可见一个大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [["光滑", "_norm_光滑"]],
        'opt_reset': {},
        'option_keys': ["_norm_光滑"],
    },
}

register_templates(_TPL, category='乳腺')
