"""自动生成 — gynecology 结构化模板"""
from template_converted import register_templates

_TPL = {
    '女性经阴道彩超（子宫附件）': {
        'html': '<div class="rpt-sec">子宫前位，形态规则，大小正常，实质回声均匀，宫腔线居中，内膜厚{_thick_0}mm，宫内未见明显异常光团及暗区。</div>',
        'fields': {"_thick_0": "腔线居中，内膜厚"},
        'measurements': [["(?:内膜厚)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_thick_0"]],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '子宫、附件未见明显异常声像。': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '双侧卵巢多囊样改变': {
        'html': '<div class="rpt-sec">右侧卵巢大小{_size_0}mm，左侧卵巢大小{_size_1}mm，双侧卵巢同一切面内可见大于十个小囊泡声像，直径约7-{_diameter_2}mm。</div>',
        'fields': {"_size_0": "右侧卵巢大小", "_size_1": "m，左侧卵巢大小", "_diameter_2": "声像，直径约7-"},
        'measurements': [["(?:右侧卵巢大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"], ["(?:左侧卵巢大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_1"], ["(?:直径约)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_diameter_2"]],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '宫颈囊肿': {
        'html': '<div class="rpt-sec">宫颈内可见无回声区，大小{_size_0}mm，壁薄，后壁回声增强，内透声可。</div>',
        'fields': {"_size_0": "见无回声区，大小"},
        'measurements': [["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '宫颈多发囊肿': {
        'html': '<div class="rpt-sec">宫颈内可见多个无回声区，较大{_较大_0}mm，壁薄，后壁回声增强，内透声可。</div>',
        'fields': {"_较大_0": "个无回声区，较大"},
        'measurements': [["(?:较大)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_较大_0"]],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '子宫肌瘤': {
        'html': '<div class="rpt-sec">子宫前壁/后壁可见低回声结节，大小{_size_0}mm，形态规则，边界清晰，内部回声欠均匀。</div>',
        'fields': {"_size_0": "低回声结节，大小"},
        'measurements': [["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [["规则", "_norm_规则"]],
        'opt_reset': {},
        'option_keys': ["_norm_规则"],
    },
    '子宫多发肌瘤': {
        'html': '<div class="rpt-sec">子宫前壁/后壁内可见多个低回声结节，较大{_较大_0}mm，形态规则，边界清晰，内部回声欠均匀。</div>',
        'fields': {"_较大_0": "低回声结节，较大"},
        'measurements': [["(?:较大)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_较大_0"]],
        'options': [["规则", "_norm_规则"]],
        'opt_reset': {},
        'option_keys': ["_norm_规则"],
    },
    '卵巢囊肿': {
        'html': '<div class="rpt-sec">左侧/右侧卵巢可见无回声区，壁薄，内壁光滑，内透声可，后壁回声增强，大小{_size_0}mm。</div>',
        'fields': {"_size_0": "壁回声增强，大小"},
        'measurements': [["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [["光滑", "_norm_光滑"]],
        'opt_reset': {},
        'option_keys': ["_norm_光滑"],
    },
    '子宫内膜声像改变': {
        'html': '<div class="rpt-sec">子宫前位/平位/后位，大小约x{_size_0}mm，内膜{_size_1}mm，局限性/弥漫性回声增强，子宫肌层为非均质性低回声，内部点状回声增粗。</div>',
        'fields': {"_size_0": "位/后位，大小约", "_size_1": "小约xmm，内膜"},
        'measurements': [["(?:大小约)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"], ["(?:内膜)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_1"]],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '子宫内膜声像改变，性质待定。': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '子宫肌瘤伴囊性变': {
        'html': '<div class="rpt-sec">子宫前位/平位/后位，大小{_size_0}mm，内膜{_size_1}mm，前壁/后壁见大小{_size_2}mm混合性结节，形态规则，边界清晰，内部回声不均匀，见不规则无回声区/强回声区。</div>',
        'fields': {"_size_0": "平位/后位，大小", "_size_1": "小约 mm，内膜", "_size_2": "前壁/后壁见大小"},
        'measurements': [["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"], ["(?:内膜)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_1"], ["(?:后壁见大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_2"]],
        'options': [["规则", "_norm_规则"]],
        'opt_reset': {},
        'option_keys': ["_norm_规则"],
    },
    '子宫肌瘤伴囊性变/钙化。': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '子宫腺肌症': {
        'html': '<div class="rpt-sec">肌壁增厚，点状回声增粗，宫腔线前移。</div>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '附件区囊肿': {
        'html': '<div class="rpt-sec">左侧/右侧附件区可见无回声区，壁薄，内壁光滑，内透声可，后壁回声增强，大小{_size_0}mm。</div>',
        'fields': {"_size_0": "壁回声增强，大小"},
        'measurements': [["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [["光滑", "_norm_光滑"]],
        'opt_reset': {},
        'option_keys': ["_norm_光滑"],
    },
    '盆腔积液': {
        'html': '<div class="rpt-sec">子宫直肠窝可见范围{_范围_0}mm液性暗区。</div>',
        'fields': {"_范围_0": "宫直肠窝可见范围"},
        'measurements': [["(?:子宫直肠窝可见范围)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_范围_0"]],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '宫颈管积液': {
        'html': '<div class="rpt-sec">宫颈管内可见宽{_width_0}mm液暗区。</div>',
        'fields': {"_width_0": "宫颈管内可见宽"},
        'measurements': [["(?:宫颈管内可见宽)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_width_0"]],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '巧克力囊肿': {
        'html': '<div class="rpt-sec">左侧/右侧卵巢可见无回声结节，形态规则，边界清，内透声差，可见细密点状回声，大小{_size_0}mm。</div>',
        'fields': {"_size_0": "密点状回声，大小"},
        'measurements': [["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [["规则", "_norm_规则"]],
        'opt_reset': {},
        'option_keys': ["_norm_规则"],
    },
    '宫内早孕': {
        'html': '<div class="rpt-sec">子宫前位，形态规则，大小正常，实质回声均匀，宫腔内可见大小{_size_0}mm孕囊声像，内可见卵黄囊及胚芽组织，长{_织长_1}mm,原始心管搏动可见。</div>',
        'fields': {"_size_0": "，宫腔内可见大小", "_织长_1": "囊及胚芽组织，长"},
        'measurements': [["(?:宫腔内可见大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"], ["(?:长)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_织长_1"]],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '子宫切口假腔': {
        'html': '<div class="rpt-sec">子宫前壁切口处可见不规则暗区，范围{_范围_0}mm，与宫腔相通。</div>',
        'fields': {"_范围_0": "不规则暗区，范围"},
        'measurements': [["(?:范围)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_范围_0"]],
        'options': [["规则", "_norm_规则"]],
        'opt_reset': {},
        'option_keys': ["_norm_规则"],
    },
    '子宫内膜息肉样病变': {
        'html': '<div class="rpt-sec">宫腔内可见一大小{_size_0}mm稍高回声结节，形态规则，边界清，内回声欠均匀。</div>',
        'fields': {"_size_0": "宫腔内可见一大小"},
        'measurements': [["(?:宫腔内可见一大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [["规则", "_norm_规则"]],
        'opt_reset': {},
        'option_keys': ["_norm_规则"],
    },
    '宫腔内稍高回声结节，考虑内膜息肉样病变。': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '子宫假腔': {
        'html': '<div class="rpt-sec">子宫前壁下段可见积液暗区，范围{_范围_0}mm，与宫腔相通，距前壁浆膜层距离{_距离_1}mm。</div>',
        'fields': {"_范围_0": "见积液暗区，范围", "_距离_1": "距前壁浆膜层距离"},
        'measurements': [["(?:范围)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_范围_0"], ["(?:距前壁浆膜层距离)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_距离_1"]],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '绝经后子宫声像': {
        'html': '<div class="rpt-sec">子宫前位，形态规则，体积缩小，实质回声均匀，宫腔线居中，内膜呈线状。</div>',
        'fields': {},
        'measurements': [],
        'options': [["规则", "_norm_规则"]],
        'opt_reset': {},
        'option_keys': ["_norm_规则"],
    },
    '绝经后子宫声像。': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '宫内妊娠单活胎2': {
        'html': '<div class="rpt-sec">子宫增大，形态饱满，实质回声均匀，宫腔内可见孕囊声像，内可见一胚胎，头臀长{_臀长_0}mm，可见胎动及胎声搏动。</div>',
        'fields': {"_臀长_0": "见一胚胎，头臀长"},
        'measurements': [["(?:头臀长)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_臀长_0"]],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '正常女性膀胱子宫附件': {
        'html': '<div class="rpt-sec">膀胱充盈可，壁光滑，内未见明显包块回声。</div>',
        'fields': {},
        'measurements': [],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '膀胱、子宫、附件未见明显异常声像。': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '子宫萎缩-ch': {
        'html': '<div class="rpt-sec">膀胱充盈可，壁光滑，内未见明显包块回声。</div>',
        'fields': {},
        'measurements': [],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '子宫萎缩。': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '绝经后子宫': {
        'html': '<div class="rpt-sec">膀胱充盈可，壁光滑，内未见明显包块回声。</div>',
        'fields': {},
        'measurements': [],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '宫颈钙化灶': {
        'html': '<div class="rpt-sec">宫颈内可见强回声斑，大小{_size_0}mm，伴声影。</div>',
        'fields': {"_size_0": "见强回声斑，大小"},
        'measurements': [["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '内膜稍毛糙。': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '双侧颈动脉内膜面稍毛糙。': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '子宫萎缩-CH': {
        'html': '<div class="rpt-sec">膀胱充盈可，壁光滑，内未见明显包块回声。</div>',
        'fields': {},
        'measurements': [],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '绝经后子宫声像-MYY': {
        'html': '<div class="rpt-sec">膀胱充盈可，壁光滑，内未见明显包块回声。</div>',
        'fields': {},
        'measurements': [],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '正常腹主动脉': {
        'html': '<div class="rpt-sec">腹主动脉内径正常，内膜光滑、未增厚，内未见明显异常回声。</div>',
        'fields': {},
        'measurements': [],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '腹主动脉斑块': {
        'html': '<div class="rpt-sec">腹主动脉内径正常，内膜毛糙，管壁增厚，腹主动脉内可见低/等/强/不均质回声斑块，大小{_size_0}mm。</div>',
        'fields': {"_size_0": "质回声斑块，大小"},
        'measurements': [["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '老年性子宫-LD': {
        'html': '<div class="rpt-sec">膀胱充盈可，壁光滑，内未见明显包块回声。</div>',
        'fields': {},
        'measurements': [],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '老年性子宫声像。': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '双下肢动脉硬化并多发斑块形成(附二)': {
        'html': '<div class="rpt-sec">双侧下肢动脉（髂外、髂股段、股、股浅、股深、腘、胫后、胫前、足背A）走行正常，管壁增厚，内膜面回声毛糙，内-中膜较厚处{_thick_0}mm，双下肢动脉内可见多个附壁强光团，较大者分别{_分别_1}mm（右）、{_约右_2}mm（左）。</div>',
        'fields': {"_thick_0": "，内-中膜较厚处", "_分别_1": "光团，较大者分别", "_约右_2": "约 mm（右）、"},
        'measurements': [["(?:中膜较厚处)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_thick_0"], ["(?:较大者分别)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_分别_1"], ["(?:右)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_约右_2"]],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '双上肢动脉硬化并多发斑块形成': {
        'html': '<div class="rpt-sec">双侧上肢（腋、肱、尺、桡动脉）走行正常，管壁增厚，内膜面回声毛糙，内-中膜较厚处{_thick_0}mm，双上肢动脉内可见多个附壁强光团，较大者分别{_分别_1}mm（右）、{_约右_2}mm（左）。</div>',
        'fields': {"_thick_0": "，内-中膜较厚处", "_分别_1": "光团，较大者分别", "_约右_2": "  mm（右）、"},
        'measurements': [["(?:中膜较厚处)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_thick_0"], ["(?:较大者分别)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_分别_1"], ["(?:右)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_约右_2"]],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '子宫发育畸形，双角子宫？（附二）': {
        'html': '<div class="rpt-sec">子宫前/后/平位，大小{_size_0}mm，横切面宫底增宽，呈“心形”凹陷，可见两个内膜回声，于宫腔上/中/下段融合，厚{_thick_1}mm，可见一个/两个宫颈管。</div>',
        'fields': {"_size_0": "/后/平位，大小", "_thick_1": "中/下段融合，厚"},
        'measurements': [["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"], ["(?:厚)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_thick_1"]],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '子宫发育畸形，双角子宫可能性大。': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '子宫右侧肌性结构，残角子宫？（附二）': {
        'html': '<div class="rpt-sec">子宫前/后/平位，大小约x{_size_0}mm，实质回声均匀，内膜线居中，厚{_thick_1}mm，宫内未见明显肿块声像。</div>\n<div class="rpt-sec">子宫右侧可见一大小{_size_2}mm肌性结构与子宫左/右侧壁相连，其中央未见/可见内膜样高回声。</div>',
        'fields': {"_size_0": "后/平位，大小约", "_thick_1": "，内膜线居中，厚", "_size_2": "宫右侧可见一大小"},
        'measurements': [["(?:大小约)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"], ["(?:厚)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_thick_1"], ["(?:子宫右侧可见一大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_2"]],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '子宫右侧肌性结构，考虑残角子宫可能性大。': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '纵隔子宫？（附二）': {
        'html': '<div class="rpt-sec">子宫前/后/平位，大小约x{_size_0}mm，实质回声均匀，横断面增宽，宫腔上段/中上段被分为左、右两部分，两侧宫角之间肌层宽{_width_1}mm，深{_width_2}mm，左右内膜厚度均{_thick_3}mm，两内膜于宫腔上/中/下段融合，宫腔内未见明显肿块声像，可见一个/两个宫颈管。</div>',
        'fields': {"_size_0": "后/平位，大小约", "_width_1": "侧宫角之间肌层宽", "_width_2": "肌层宽约mm，深", "_thick_3": "，左右内膜厚度均"},
        'measurements': [["(?:大小约)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"], ["(?:两侧宫角之间肌层宽)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_width_1"], ["(?:深)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_width_2"], ["(?:左右内膜厚度均)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_thick_3"]],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '子宫发育畸形，纵隔子宫可能性大。': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '子宫异位征（附二）': {
        'html': '<div class="rpt-sec">盆腔未探及正常子官声像，膀胱后方可见一个低回声条索状物，大小{_size_0}mm，实质回声均匀，内未见明显内膜线回声。</div>',
        'fields': {"_size_0": "声条索状物，大小"},
        'measurements': [["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '子宫异位征': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '双子宫？（附二）': {
        'html': '<div class="rpt-sec">盆腔内可见两个宫体、两个宫颈声像，两个宫腔不相通，左侧子宫前/后/平位，大小{_size_0}mm，实质回声均匀，内膜线居中，厚{_thick_1}mm，宫内未见明显肿块图像。</div>\n<div class="rpt-sec">右侧子宫前/后/平位，大小约x{_size_2}mm，实质回声均匀，内膜线居中，厚{_thick_3}mm，宫内未见明显肿块图像。</div>',
        'fields': {"_size_0": "/后/平位，大小", "_thick_1": "，内膜线居中，厚", "_size_2": "后/平位，大小约", "_thick_3": "，内膜线居中，厚"},
        'measurements': [["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"], ["(?:厚)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_thick_1"], ["(?:大小约)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_2"], ["(?:厚)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_thick_3"]],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '巧克力囊肿（附二）': {
        'html': '<div class="rpt-sec">子宫前/后/平位，大小约x{_size_0}mm，实质回声均匀，内膜线居中，厚{_thick_1}mm，宫内及肌壁未见明显肿块声像。</div>',
        'fields': {"_size_0": "后/平位，大小约", "_thick_1": "，内膜线居中，厚"},
        'measurements': [["(?:大小约)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"], ["(?:厚)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_thick_1"]],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '腹主动脉瘤': {
        'html': '<div class="rpt-sec">腹主动脉部分节段内径瘤样扩张，内径{_diameter_0}mm，与正常段内径比值：，其扩张段暂未见明显血栓及斑块，余管腔内膜光滑、未增厚，内未见明显异常回声。</div>',
        'fields': {"_diameter_0": "径瘤样扩张，内径"},
        'measurements': [["(?:内径)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_diameter_0"]],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
}

register_templates(_TPL, category='妇科')
