"""自动生成 — thyroid 结构化模板"""
from template_converted import register_templates

_TPL = {
    '甲状腺(正常)': {
        'html': '<div class="rpt-sec">甲状腺双侧叶形态规则，大小正常，表面光滑，实质回声分布均匀，内未见明显结节及占位回声。</div>',
        'fields': {},
        'measurements': [],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '甲状腺、甲状旁腺、颈部淋巴结未见异常（有淋巴结）': {
        'html': '<div class="rpt-sec">甲状腺双侧叶形态规则，大小正常，表面光滑，实质回声分布均匀，内未见明显结节及占位回声。</div>',
        'fields': {},
        'measurements': [],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '甲状腺、双侧颈动脉、乳腺未见异常（有淋巴结）': {
        'html': '<div class="rpt-sec">甲状腺双侧叶切面形态规则，大小正常，表面光滑，实质回声分布均匀，内未见明显结节及其它异常回声。</div>\n<div class="rpt-sec">双侧颈部未见明显淋巴结回声。</div>',
        'fields': {},
        'measurements': [],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '6': {
        'html': '<b class="rpt-label">正常甲状腺、颈动脉、乳腺</b>',
        'fields': {},
        'measurements': [],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '3': {
        'html': '<b class="rpt-label">正常甲状腺、颈动脉、乳腺</b>',
        'fields': {},
        'measurements': [],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '甲状腺单发结节': {
        'html': '<div class="rpt-sec">甲状腺双侧叶形态规则，大小正常，表面光滑，包膜完整,内部回声均匀，侧叶内可见回声结节，大小{_size_0}mm，形态规则，边界清晰，内部回声欠均匀。</div>\n<div class="rpt-sec">CDFI:甲状腺结节内未见明显血流信号/周边见点状血流信号。</div>\n<div class="rpt-sec">双侧颈部未见明显肿大淋巴结。</div>',
        'fields': {"_size_0": "见回声结节，大小"},
        'measurements': [["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '2': {
        'html': '<b class="rpt-label">甲状腺疾病</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '甲状腺双侧叶多发结节': {
        'html': '<div class="rpt-sec">甲状腺双侧叶形态规则，大小正常，表面光滑，包膜完整，内部回声欠均匀，甲状腺双侧叶内可见多个低/混合回声结节，形态规则，边界清晰，内部回声欠均匀，较大{_较大_0}mm（左）、{_约左_1}mm（右）。</div>',
        'fields': {"_较大_0": "回声欠均匀，较大", "_约左_1": "约 mm（左）、"},
        'measurements': [["(?:较大)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_较大_0"], ["(?:左)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_约左_1"]],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '5': {
        'html': '<b class="rpt-label">甲状腺疾病</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '甲状腺无回声结节（单发）': {
        'html': '<div class="rpt-sec">甲状腺双侧叶形态规则，大小正常，表面光滑，包膜完整，内部回声均匀，左/右侧叶内可见无回声结节，大小{_size_0}mm，形态规则，边界清晰，内透声可。</div>',
        'fields': {"_size_0": "无回声结节，大小"},
        'measurements': [["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '4': {
        'html': '<b class="rpt-label">甲状腺疾病</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '桥本氏甲状腺炎': {
        'html': '<div class="rpt-sec">甲状腺双侧叶形态规则，大小正常/体积增大，表面光滑，包膜完整，腺体内点状回声增强，分布不均，见多个稍高回声带，呈网格状/筛窦状改变。</div>',
        'fields': {},
        'measurements': [],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '甲状腺功能亢进': {
        'html': '<div class="rpt-sec">甲状腺双侧叶形态欠/不规则，大小正常/体积增大，表面光滑，包膜完整，腺体内点状回声增强，分布不均，呈弥漫性改变，未见占位性病变。</div>',
        'fields': {},
        'measurements': [],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '甲状腺腺瘤': {
        'html': '<div class="rpt-sec">甲状腺左侧叶/右侧叶内见一大小{_size_0}mm低回声/等回声/稍高回声区，边界清晰，包膜完整，周边有声晕，内部回声分布欠均。</div>',
        'fields': {"_size_0": "右侧叶内见一大小"},
        'measurements': [["(?:右侧叶内见一大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [["清晰", "_norm_清晰"]],
        'opt_reset': {},
        'option_keys': ["_norm_清晰"],
    },
    '1': {
        'html': '<b class="rpt-label">甲状腺疾病</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '甲状腺低回声/不均质回声结节': {
        'html': '<div class="rpt-sec">甲状腺左侧叶/右侧叶内见一大小{_size_0}mm低回声/不均质回声结节，形态不规则，边界不清晰，呈锯齿状，后方回声衰减。</div>',
        'fields': {"_size_0": "右侧叶内见一大小"},
        'measurements': [["(?:右侧叶内见一大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [["规则", "_norm_规则"]],
        'opt_reset': {},
        'option_keys': ["_norm_规则"],
    },
    '甲状腺回声不均匀': {
        'html': '<div class="rpt-sec">甲状腺双侧叶形态规则，大小正常，表面光滑，实质回声不均匀，内未见明显结节及占位回声。</div>',
        'fields': {},
        'measurements': [],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '亚急性甲状腺炎': {
        'html': '<div class="rpt-sec">甲状腺双侧叶切面形态规则，表面光滑，大小正常，实质点状回声增粗、增强，分布欠均匀，内见一个/多个片状低回声区，形态欠规则，边界欠清，内分布欠均匀。</div>',
        'fields': {},
        'measurements': [],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '甲状腺双侧叶无回声结节': {
        'html': '<div class="rpt-sec">甲状腺双侧叶形态规则，大小正常,表面光滑，包膜完整，内部回声欠均匀，双侧叶内可见无回声结节，形态规则，边界清晰，内透声可，大小分别{_size_0}mm（左侧叶）、{_侧叶_1}mm（右侧叶）。</div>\n<div class="rpt-sec">CDFI:甲状腺结节内未见明显血流信号。</div>\n<div class="rpt-sec">双侧颈部未见明显肿大淋巴结回声。</div>',
        'fields': {"_size_0": "透声可，大小分别", "_侧叶_1": "mm（左侧叶）、"},
        'measurements': [["(?:大小分别)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"], ["(?:左侧叶)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_侧叶_1"]],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '甲状腺结节-3类': {
        'html': '<div class="rpt-sec">甲状腺双侧叶形态规则，大小正常，表面光滑，包膜完整，内部回声均匀，左/右侧叶内可见低/混合回声结节，大小{_size_0}mm，形态规则，边界清晰，内部回声欠均匀。</div>',
        'fields': {"_size_0": "合回声结节，大小"},
        'measurements': [["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '甲状腺体积增大': {
        'html': '<div class="rpt-sec">甲状腺双侧叶形态饱满，体积增大，左侧叶大小约x{_size_0}mm，右侧叶大小约x{_size_1}mm，峡部厚{_size_2}mm，表面光滑，实质回声分布均匀，内未见明显结节及占位回声。</div>',
        'fields': {"_size_0": "大，左侧叶大小约", "_size_1": "m，右侧叶大小约", "_size_2": "约xmm，峡部厚"},
        'measurements': [["(?:左侧叶大小约)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"], ["(?:右侧叶大小约)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_1"], ["(?:峡部厚)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_2"]],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '甲状腺体积缩小': {
        'html': '<div class="rpt-sec">甲状腺双侧叶形态失常，体积缩小，左侧叶大小约x{_size_0}mm，右侧叶大小约x{_size_1}mm，峡部厚{_size_2}mm，表面光滑，实质回声分布均匀，内未见明显结节及占位回声。</div>',
        'fields': {"_size_0": "小，左侧叶大小约", "_size_1": "m，右侧叶大小约", "_size_2": "约xmm，峡部厚"},
        'measurements': [["(?:左侧叶大小约)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"], ["(?:右侧叶大小约)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_1"], ["(?:峡部厚)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_2"]],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '甲状腺全切术后': {
        'html': '<div class="rpt-sec">受检者自述甲状腺已切除。</div>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '甲状腺实质性结节（CH）': {
        'html': '<div class="rpt-sec">甲状腺双侧叶形态规则，大小正常，表面光滑，包膜完整，内部回声均匀；</div>\n<div class="rpt-sec">左/右侧叶上/中/下部可见低回声结节，大小{_size_0}mm，形态规则，边缘清晰，内部回声欠均匀。</div>',
        'fields': {"_size_0": "低回声结节，大小"},
        'measurements': [["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '甲状腺单结节模板': {
        'html': '<div class="rpt-sec">左/右侧叶内可见低/混合回声结节，形态规则，边界清晰，内部回声欠均匀，大小{_size_0}mm。</div>',
        'fields': {"_size_0": "回声欠均匀，大小"},
        'measurements': [["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [["规则", "_norm_规则"]],
        'opt_reset': {},
        'option_keys': ["_norm_规则"],
    },
    '甲状腺左/右侧叶结节，TI-RADS 3类。': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '甲状腺无回声结节（多发）': {
        'html': '<div class="rpt-sec">甲状腺双侧叶形态规则，大小正常，表面光滑，包膜完整，内部回声均匀，左/右侧叶内可见多个无回声结节，形态规则，边界清晰，内透声可，其一大小{_size_0}mm。</div>',
        'fields': {"_size_0": "透声可，其一大小"},
        'measurements': [["(?:其一大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '甲状腺低-无回声结节-陈': {
        'html': '<div class="rpt-sec">甲状腺双侧叶形态规则，大小正常，表面光滑，包膜完整，内部回声均匀，左侧叶/右侧叶内可见一低-无回声结节，形态规则，边界清晰，内部回声欠均匀，纵横比大于/小于1，有/无细小钙化，大小{_size_0}mm。</div>',
        'fields': {"_size_0": "无细小钙化，大小"},
        'measurements': [["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '甲状腺实质弥漫性病变': {
        'html': '<div class="rpt-sec">甲状腺双侧叶切面形态规则，表面光滑，大小正常，实质点状回声增粗、增强，分布不均匀，内见多个片状低回声区。</div>',
        'fields': {},
        'measurements': [],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '甲状腺无回声结节单模板': {
        'html': '<div class="rpt-sec">左/右侧叶内可见一个无回声结节，形态规则，边界清晰，内透声可，大小{_size_0}mm。</div>',
        'fields': {"_size_0": "，内透声可，大小"},
        'measurements': [["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [["规则", "_norm_规则"]],
        'opt_reset': {},
        'option_keys': ["_norm_规则"],
    },
    '甲状腺左/右侧叶结节，TI-RADS 2类。': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '甲状腺低回声区': {
        'html': '<div class="rpt-sec">甲状腺双侧叶形态规则，大小正常，表面光滑，包膜完整，内部回声均匀，左/右侧叶内可见低回声区，形态规则，边界清晰，内部回声欠均匀，大小{_size_0}mm。</div>',
        'fields': {"_size_0": "回声欠均匀，大小"},
        'measurements': [["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '甲状腺混合回声结节（CH）': {
        'html': '<div class="rpt-sec">甲状腺双侧叶形态规则，大小正常，表面光滑，包膜完整，内部回声均匀；</div>\n<div class="rpt-sec">左/右侧叶上/中/下部可见混合性结节，大小{_size_0}mm，形态规则，边缘清晰，内部回声欠均匀。</div>',
        'fields': {"_size_0": "混合性结节，大小"},
        'measurements': [["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '甲状腺囊性结节（CH）': {
        'html': '<div class="rpt-sec">甲状腺双侧叶形态规则，大小正常，表面光滑，包膜完整，内部回声均匀，左/右侧叶中/上/下部可见囊性结节，大小{_size_0}mm，形态规则，边界清晰，内透声可。</div>',
        'fields': {"_size_0": "见囊性结节，大小"},
        'measurements': [["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '甲状腺多发结节': {
        'html': '<div class="rpt-sec">甲状腺双侧叶形态规则，大小正常，表面光滑，包膜完整，内部回声均匀，左/右侧叶内可见多个低/混合回声结节，形态规则，边界清晰，内部回声欠均匀，其一大小{_size_0}mm。</div>',
        'fields': {"_size_0": "欠均匀，其一大小"},
        'measurements': [["(?:其一大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '甲状腺多发囊性结节（CH）': {
        'html': '<div class="rpt-sec">甲状腺双侧叶形态规则，大小正常，表面光滑，包膜完整,内部回声均匀，左/右侧叶可见多个囊性结节，较大位于中/上/下部，大小{_size_0}mm，形态规则，边界清晰，内透声可。</div>\n<div class="rpt-sec">CDFI:甲状腺结节内无明显血流信号。</div>\n<div class="rpt-sec">双侧颈部未见明显肿大淋巴结。</div>',
        'fields': {"_size_0": "/上/下部，大小"},
        'measurements': [["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '桥本': {
        'html': '<div class="rpt-sec">甲状腺双侧叶形态规则，大小正常，表面光滑，包膜完整，实质光点增粗，分布不均，呈网格状改变，内未见明显结节回声。</div>',
        'fields': {},
        'measurements': [],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '甲亢': {
        'html': '<div class="rpt-sec">甲状腺形态饱满，左侧叶大小{_size_0}mm，右侧叶x{_size_1}mm，峡部{_峡部_2}mm，实质光点增粗，回声中等/增强/减低，分布不均匀，未见明显结节回声。</div>',
        'fields': {"_size_0": "饱满，左侧叶大小", "_size_1": "小约mm，右侧叶", "_峡部_2": "侧叶xmm，峡部"},
        'measurements': [["(?:左侧叶大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"], ["(?:右侧叶)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_1"], ["(?:峡部)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_峡部_2"]],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '甲状腺功能亢进。': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '甲状腺单纯性肿大': {
        'html': '<div class="rpt-sec">甲状腺形态饱满，表面光滑，包膜完整，左侧叶大小 ×{_size_0}mm，右侧叶{_size_1}mm，峡部{_size_2}mm。</div>\n<div class="rpt-sec">实质光点细致，回声分布均匀，未见明肿块图像。</div>',
        'fields': {"_size_0": "完整，左侧叶大小", "_size_1": "× mm，右侧叶", "_size_2": "叶大小mm，峡部"},
        'measurements': [["(?:左侧叶大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"], ["(?:右侧叶)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_1"], ["(?:峡部)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_2"]],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '甲状腺弥漫性肿大': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '甲状旁腺': {
        'html': '<div class="rpt-sec">双侧甲状旁腺区未见明显占位性病变。</div>',
        'fields': {},
        'measurements': [],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
}

register_templates(_TPL, category='甲状腺')
