"""自动生成 — vascular 结构化模板"""
from template_converted import register_templates

_TPL = {
    '双侧颈动脉内中膜增厚': {
        'html': '<div class="rpt-sec">双侧颈动脉（颈总、颈内、颈外动脉）走行正常，内膜面光滑，内-中膜非均质性增厚，较厚处分别{_thick_0}mm（左）、{_约左_1}mm（右），管腔内无明显斑块回声，未见明显狭窄及扩张。</div>',
        'fields': {"_thick_0": "增厚，较厚处分别", "_约左_1": "  mm（左）、"},
        'measurements': [["(?:较厚处分别)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_thick_0"], ["(?:左)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_约左_1"]],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '双侧颈动脉内-中膜增厚。': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '双侧颈动脉粥样硬化伴多发斑块形成': {
        'html': '<div class="rpt-sec">双侧颈动脉（颈总、颈内、颈外动脉）走行正常，内膜面毛糙，内-中膜非均质性增厚，较厚处分别{_thick_0}mm（左）、{_约左_1}mm（右），双侧颈总动脉内见多个 回声斑块，较大{_较大_2}mm（左），较大{_较大_3}mm（右），形态规则/不规则，内回声均匀/边界清，纤维帽完整/不完整。</div>',
        'fields': {"_thick_0": "增厚，较厚处分别", "_约左_1": "  mm（左）、", "_较大_2": " 回声斑块，较大", "_较大_3": "mm（左），较大"},
        'measurements': [["(?:较厚处分别)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_thick_0"], ["(?:左)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_约左_1"], ["(?:较大)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_较大_2"], ["(?:较大)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_较大_3"]],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '双侧颈动脉粥样硬化并多发斑块形成。': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '下肢血管': {
        'html': '<div class="rpt-sec">双下肢股总动脉、股深动脉、股浅动脉、腘动脉及其分支走行规则，管壁光滑，管腔无明显扩张或狭窄，内未见明显异常回声。</div>',
        'fields': {},
        'measurements': [],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '双侧椎动脉未见异常': {
        'html': '<div class="rpt-sec">双侧椎动脉走行正常，内径对称，形态规则，内壁光滑，内未见斑块、狭窄、扩张及其他异常回声。</div>',
        'fields': {},
        'measurements': [],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '双侧椎动脉未见明显异常声像。': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '椎动脉疾病': {
        'html': '<div class="rpt-sec">双侧椎动脉局部走行弯曲/正常，右侧椎动脉{_动脉_0}mm，血流阻力值：0cm/s，左侧椎动脉{_动脉_1}mm，阻力值：cm/s，形态规则，内壁光滑，内未见斑块、增厚、狭窄、扩张及其他异常回声。</div>',
        'fields': {"_动脉_0": "正常，右侧椎动脉", "_动脉_1": "/s，左侧椎动脉"},
        'measurements': [["(?:右侧椎动脉)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_动脉_0"], ["(?:左侧椎动脉)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_动脉_1"]],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '椎动脉内径狭窄': {
        'html': '<div class="rpt-sec">双侧椎动脉内径不对称，右侧椎动脉{_diameter_0}mm，左侧椎动脉{_diameter_1}mm，椎动脉局部走行正常,形态规则，内壁光滑，内未见斑块、增厚、扩张及其他异常回声。</div>\n<div class="rpt-sec">CDFI：双侧椎动脉血流速度正常，内血彩未见充盈缺损。</div>',
        'fields': {"_diameter_0": "对称，右侧椎动脉", "_diameter_1": "mm，左侧椎动脉"},
        'measurements': [["(?:右侧椎动脉)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_diameter_0"], ["(?:左侧椎动脉)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_diameter_1"]],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '双侧颈动脉硬化': {
        'html': '<div class="rpt-sec">双侧颈总动脉及颈内外动脉起始段走行正常，管壁增厚，内膜面欠光滑，内膜回声增强，内-中膜较厚处{_thick_0}mm(左)、{_thick_1}mm（右），其内未见明显异常。</div>',
        'fields': {"_thick_0": "，内-中膜较厚处", "_thick_1": "处约mm(左)、"},
        'measurements': [["(?:中膜较厚处)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_thick_0"], ["(?:左)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_thick_1"]],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '双侧颈动脉硬化。': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '颈动脉斑块形成(6根）': {
        'html': '<div class="rpt-sec">双侧颈动脉（颈总、颈内、颈外动脉）走行正常，内膜面毛糙，内-中膜局部非均质性增厚，较厚处分别{_thick_0}mm（左）、{_约左_1}mm（右），左/右侧颈动脉膨大处、窦部后壁/前壁/内侧壁、分叉处、主干，颈内动脉起始部内可见低/等/强/不均质回声斑块，大小{_size_2}mm。</div>',
        'fields': {"_thick_0": "增厚，较厚处分别", "_约左_1": "  mm（左）、", "_size_2": "质回声斑块，大小"},
        'measurements': [["(?:较厚处分别)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_thick_0"], ["(?:左)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_约左_1"], ["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_2"]],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '颈动脉血流异常模板': {
        'html': '<div class="rpt-sec">双侧颈动脉（颈总、颈内、颈外动脉）走形正常，内-中膜不均匀增厚，双侧管腔内探及多发大小不等，回声不均斑块，右侧最大者位于，其大小{_size_0}mm：左侧最大者位于，其大小{_size_1}mm。</div>\n<div class="rpt-sec">狭窄处{_窄处_2}mm。</div>',
        'fields': {"_size_0": "大者位于，其大小", "_size_1": "大者位于，其大小", "_窄处_2": "狭窄处"},
        'measurements': [["(?:其大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"], ["(?:其大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_1"], ["(?:狭窄处)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_窄处_2"]],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '颈总/颈内/颈外动脉狭窄（轻/中/重）。': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '右侧锁骨下动脉斑块形成': {
        'html': '<div class="rpt-sec">右侧锁骨下动脉起始处可见  回声斑块，大小{_size_0}mm。</div>',
        'fields': {"_size_0": " 回声斑块，大小"},
        'measurements': [["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '右侧锁骨下动脉斑块形成。': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '椎动脉细窄、不对称（陈）': {
        'html': '<div class="rpt-sec">左/右侧椎动脉走行正常，左/右侧椎动脉内径{_diameter_0}mm，形态规则，内壁光滑，内未见斑块、增厚、狭窄、扩张及其他异常回声。</div>',
        'fields': {"_diameter_0": "/右侧椎动脉内径"},
        'measurements': [["(?:右侧椎动脉内径)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_diameter_0"]],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '颈+椎+锁骨下动脉正常': {
        'html': '<div class="rpt-sec">双侧颈动脉（颈总动脉、颈内动脉、颈外动脉）、锁骨下动脉走行正常，内膜光滑，内-中膜无增厚，未见明显狭窄及扩张，管腔内无明显斑块回声。</div>',
        'fields': {},
        'measurements': [],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '颈动脉正常（颈+锁骨下）': {
        'html': '<div class="rpt-sec">双侧颈动脉（颈总动脉、颈内动脉、颈外动脉）、锁骨下动脉走行正常，内膜光滑，内-中膜未增厚，管腔内无明显斑块声像，未见明显狭窄及扩张。</div>',
        'fields': {},
        'measurements': [],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '双侧颈总动脉、颈内动脉、颈外动脉、锁骨下动脉未见明显异常声像。': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '颈动脉斑块单模板': {
        'html': '<div class="rpt-sec">左/右侧颈总动脉膨大处、窦部、分叉处、主干，颈内动脉起始部内可见低/等/强/不均质回声斑块，大小{_size_0}mm。</div>',
        'fields': {"_size_0": "质回声斑块，大小"},
        'measurements': [["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '左/右侧颈动脉斑块形成。': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '颈动脉单斑块+锁骨下': {
        'html': '<div class="rpt-sec">双侧颈动脉（颈总、颈内、颈外动脉）走行正常，内膜面光滑，内中膜不厚，左侧/右侧颈动脉内可见等/低/不均质回声斑块，大小{_size_0}mm。</div>',
        'fields': {"_size_0": "质回声斑块，大小"},
        'measurements': [["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '颈动脉内中膜稍增厚（简单版）': {
        'html': '<div class="rpt-sec">双侧颈动脉（颈总、颈内、颈外动脉）走行正常，内膜面稍毛糙，内-中膜稍增厚，较厚处分别{_thick_0}mm（左）、{_约左_1}mm（右），管腔内无明显斑块回声，未见明显狭窄及扩张。</div>',
        'fields': {"_thick_0": "增厚，较厚处分别", "_约左_1": "  mm（左）、"},
        'measurements': [["(?:较厚处分别)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_thick_0"], ["(?:左)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_约左_1"]],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '双侧颈动脉内中膜稍增厚。': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '颈总动脉狭窄': {
        'html': '<div class="rpt-sec">双侧颈动脉（颈总、颈内、颈外动脉）走行正常，内膜面不光滑，内中膜不规则增厚，较厚处{_thick_0}mm（左）、{_thick_1}mm（右）， 侧颈总动脉窦部可见回声斑块，大小{_size_2}mm，管腔局部狭窄，原始管径{_diameter_3}mm，残余管径{_diameter_4}mm。</div>',
        'fields': {"_thick_0": "规则增厚，较厚处", "_thick_1": "处约mm（左）、", "_size_2": "见回声斑块，大小", "_diameter_3": "部狭窄，原始管径", "_diameter_4": " mm，残余管径"},
        'measurements': [["(?:较厚处)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_thick_0"], ["(?:左)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_thick_1"], ["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_2"], ["(?:原始管径)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_diameter_3"], ["(?:残余管径)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_diameter_4"]],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '侧颈总动脉斑块形成并局部轻-中度狭窄。': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '（纤维成分为主）斑块': {
        'html': '<div class="rpt-sec">双侧颈动脉（颈总、颈内、颈外动脉）走行正常，内膜面毛糙，内中膜不厚，左侧/右侧颈总动脉分叉处及右侧/左侧颈内动脉起始部内可见中等回声附壁光团不移动，纤维帽连续，大小{_size_0}mm。</div>',
        'fields': {"_size_0": "纤维帽连续，大小"},
        'measurements': [["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '左侧/右侧颈总动脉分叉处粥样硬化斑块（纤维成分为主）。': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '颈动脉（钙化斑）': {
        'html': '<div class="rpt-sec">双侧颈动脉（颈总、颈内、颈外动脉）走行正常，内膜面毛糙，内中膜不厚，左侧/右侧颈总动脉分叉处可见大小{_size_0}mm附壁强光斑伴声影。</div>',
        'fields': {"_size_0": "脉分叉处可见大小"},
        'measurements': [["(?:侧颈总动脉分叉处可见大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '左侧/右侧颈总动脉分叉处粥样硬化斑块（钙化斑块）。': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '双侧颈动脉硬化伴斑块形成': {
        'html': '<div class="rpt-sec">双侧颈动脉（颈总、颈内、颈外动脉）走行正常，内膜面毛糙，内-中膜局部非均质性增厚，较厚处分别{_thick_0}mm（左）、{_thick_1}mm（右），双侧颈总动脉窦部后壁内可见强回声斑块，大小{_size_2}mm(左)、{_size_3}mm(右)。</div>',
        'fields': {"_thick_0": "增厚，较厚处分别", "_thick_1": "别约mm（左）、", "_size_2": "强回声斑块，大小", "_size_3": "小约mm(左)、"},
        'measurements': [["(?:较厚处分别)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_thick_0"], ["(?:左)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_thick_1"], ["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_2"], ["(?:左)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_3"]],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '双侧颈动脉硬化伴斑块形成。': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '椎动脉内径不对称': {
        'html': '<div class="rpt-sec">双侧椎动脉走行正常，内径不对称，宽分别{_width_0}mm(右）、{_width_1}mm（左），形态规则，内壁光滑，内未见斑块、狭窄、扩张及其他异常回声。</div>',
        'fields': {"_width_0": "径不对称，宽分别", "_width_1": "约 mm(右）、"},
        'measurements': [["(?:宽分别)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_width_0"], ["(?:右)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_width_1"]],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '双侧椎动脉内径不对称。': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '（脂质成分为主，易损斑块）': {
        'html': '<div class="rpt-sec">双侧颈动脉（颈总、颈内、颈外动脉）走行正常，内膜光滑，内中膜未增厚，右侧/左侧颈总动脉分叉处可见{_可见_0}mm的低-无回声为主的附壁光团不移动，纤维帽连续。</div>',
        'fields': {"_可见_0": "总动脉分叉处可见"},
        'measurements': [["(?:左侧颈总动脉分叉处可见)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_可见_0"]],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '左侧/右侧颈总动脉分叉处粥样硬化斑块形成（脂质成分为主，易损斑块）': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '内膜稍毛糙': {
        'html': '<div class="rpt-sec">双侧颈动脉（颈总、颈内、颈外动脉）走行正常，内膜稍毛糙，内中膜未增厚，管腔内无明显斑块声像，未见明显狭窄及扩张。</div>',
        'fields': {},
        'measurements': [],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '双侧颈动脉内膜稍毛糙': {
        'html': '<div class="rpt-sec">双侧颈动脉（颈总、颈内、颈外动脉）走行正常，内膜面稍毛糙，内-中膜不厚，管腔内无明显斑块声像，未见明显狭窄及扩张。</div>',
        'fields': {},
        'measurements': [],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '腹主动脉硬化并斑块形成。': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '右侧/左侧内中膜增厚并斑块形成': {
        'html': '<div class="rpt-sec">双侧颈动脉（颈总、颈内、颈外动脉）走行正常，内膜面毛糙，右侧/左侧内-中膜增厚，较厚{_thick_0}mm，右侧/左侧颈总动脉内可见 回声斑块，大小{_size_1}mm。</div>',
        'fields': {"_thick_0": "-中膜增厚，较厚", "_size_1": " 回声斑块，大小"},
        'measurements': [["(?:较厚)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_thick_0"], ["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_1"]],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '右侧/左侧颈动脉内中膜增厚并斑块形成。': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '双侧下肢动脉硬化并多发斑块形成。': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '双侧上肢动脉硬化并多发斑块形成。': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '颈动脉斑块形成（申）': {
        'html': '<div class="rpt-sec">双侧颈动脉（颈总、颈内、颈外动脉）走行正常，内膜面光滑，内中膜不厚，左侧/右侧颈动脉窦部可见低回声斑块，大小{_size_0}mm，纤维帽连续，内部回声均匀。</div>',
        'fields': {"_size_0": "低回声斑块，大小"},
        'measurements': [["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
    '左侧/右侧颈动脉窦部斑块形成。': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '右侧锁骨下动脉斑块形成（申）': {
        'html': '<div class="rpt-sec">右侧锁骨下动脉起始处可见  回声斑块，大小{_size_0}mm，纤维帽连续，内部回声尚均匀。</div>',
        'fields': {"_size_0": " 回声斑块，大小"},
        'measurements': [["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '右锁骨下动脉起始处斑块形成。': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '正常颈动脉': {
        'html': '<div class="rpt-sec">双侧颈动脉（颈总、颈内、颈外动脉）走行正常，内膜光滑，内-中膜未增厚，管腔内无明显斑块声像，未见明显狭窄及扩张。</div>',
        'fields': {},
        'measurements': [],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '双侧颈总动脉、颈内动脉、颈外动脉未见明显异常声像。': {
        'html': '<b class="rpt-label">0</b>',
        'fields': {},
        'measurements': [],
        'options': [],
        'opt_reset': {},
        'option_keys': [],
    },
    '正常颈动脉（颈+椎动脉）': {
        'html': '<div class="rpt-sec">双侧颈动脉（颈总、颈内、颈外动脉）走行正常，内膜光滑，内-中膜无增厚，未见明显狭窄及扩张，管腔内无明显斑块回声。</div>',
        'fields': {},
        'measurements': [],
        'options': [["未见", "_norm_未见"]],
        'opt_reset': {},
        'option_keys': ["_norm_未见"],
    },
    '颈动脉斑块（单独）': {
        'html': '<div class="rpt-sec">双侧颈动脉（颈总、颈内、颈外动脉）走行正常，内膜面光滑，内中膜不厚，左侧/右侧颈动脉内可见等/低/不均质回声斑块，大小{_size_0}mm。</div>',
        'fields': {"_size_0": "质回声斑块，大小"},
        'measurements': [["(?:大小)\\s*(?:约|为|是|大)?\\s*(\\d+(?:\\.\\d+)?)\\s*(?:mm|毫米|cm|厘米)", "_size_0"]],
        'options': [["正常", "_norm_正常"]],
        'opt_reset': {},
        'option_keys': ["_norm_正常"],
    },
}

register_templates(_TPL, category='血管')
